import Head from "next/head";
import Header from "@/components/Header";
import Customers from "@/components/Customers";

export default function Home() {
  return (
    <>
      <Head>
        <title>react-test-task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="body_container">
        <Header></Header>
        <main className="main_container">
          <h1 className="greeting">Hello Evano 👋🏼,</h1>
          <Customers />
        </main>
      </div>
    </>
  );
}
